### ISSUE TITLE
Remove typing effect from home page.

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/brackets#6]

**Comment by jeremyboggs** [comment]
Adding the help-wanted label, as I believe @mk7kf has ideas for this before we remove it entirely.

**Comment by mk7kf** [comment]
Could we see what the animation might look like with the following changes?

1. Remove the typing indicator line at the end
2. Put FIXED brackets on each side of the screen like so: [                   ]. These brackets will not move in the animation, they stay fixed, and the point of this change is so that viewer visually expects something to go in between the brackets. This would visually articulate the broader message of the project in a stronger way: that is, our aim to encourage people to get their own names "out there" through a personal website. 
3. In between the brackets is where our names will be "typed out" as they are currently are
4. And then the animation ends with Your Name Here being typed out, and it stays put on the screen.

As of right now it the animation might be confusing for someone coming to our site for the first time because they're just seeing six random names being typed out, but with the visual cue of the fixed brackets, this might entice the viewer to wait and see what will happen, and also immediately implies that something should be going into those brackets -- and of course by the end the viewer finds out that what is supposed to go there is their own name.

**Comment by jeremyboggs** [comment]
@shane-et-al What do you think? Adding you to the assignee list.

**Comment by jeremyboggs** [comment]
Closing this as fixed in 8c8fb61. If there are other specific changes for the title animation, let's open a new ticket with those details.
